# Generated by Django 4.2.14 on 2024-07-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedimage',
            old_name='image',
            new_name='original_image',
        ),
        migrations.RemoveField(
            model_name='uploadedimage',
            name='detection_result',
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='result_image',
            field=models.ImageField(default='default_result_image.png', upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
