# Generated by Django 4.2.14 on 2024-07-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detection_app', '0002_rename_image_uploadedimage_original_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadedimage',
            old_name='original_image',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='uploadedimage',
            name='result_image',
        ),
        migrations.AddField(
            model_name='uploadedimage',
            name='detection_result',
            field=models.ImageField(blank=True, null=True, upload_to='results/'),
        ),
    ]
